[package]
name = "day02"
version = "0.1.0"
authors = ["drewsteinacher <drewsteinacher@gmail.com>"]
edition = "2018"

[dependencies]
maplit = "1.0.1"
strsim = "0.9.2"
itertools = "0.8.0"
array_tool = "1.0.3"